# Generated by Django 5.1.3 on 2024-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='movie_photos/'),
        ),
    ]
